image:
  - Visual Studio 2017

platform:
    - x64

environment:
    fast_finish: true
    matrix:
        - VSVER: 15

configuration:
    - shared

before_build:
    - ps: >-
        Install-Module VSSetup -Scope CurrentUser
    - ps: >-
        Get-VSSetupInstance -All
    - ps: >-
        gci env:* | sort-object name
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
    - mkdir _build
    - cd _build
    - perl ..\Configure VC-WIN64A-masm no-makedepend
    - perl configdata.pm --dump
    - cd ..

build_script:
    - cd _build
    - cmd /c "nmake build_all_generated 2>&1"
    - cmd /c "nmake PERL=no-perl 2>&1"
    - cd ..

test_script:
    - cd _build
    - cmd /c "nmake test HARNESS_VERBOSE_FAILURE=yes TESTS=-test_fuzz 2>&1"
    - mkdir ..\_install
    - cmd /c "nmake install DESTDIR=..\_install 2>&1"
    - cd ..
